### PR TITLE
Added my name to the README file

### PR DESCRIPTION
**Pull request by KristopherKohlmeier**

### CODE REVIEW

**Review by HarrisonPower — COMMENTED** [review]
Looks good!

**Review by HarrisonPower — APPROVED** [review]
Approved

**Comment by jordan206** [comment]
Ah, just found the button. Thanks.

**Comment by jordan206** [comment]
Wait that was the wrong button.

**Review by jordan206 — APPROVED** [review]
Shipshape.

**Comment by jordan206** [comment]
I'm gonna let Anton figure this one out.

**Pull request merged**
